### ISSUE TITLE
Cant execute the binary

### ISSUE THREAD

**Issue by ghost** [MrNex/NGen#37]
When I try to start it I get this error:
X Error of failed request:  GLXBadFBConfig
  Major opcode of failed request:  155 (GLX)
  Minor opcode of failed request:  34 ()
  Serial number of failed request:  38
  Current serial number in output stream:  37

**Comment by MrNex** [comment]
Does your hardware support OpenGL 4.3 core profile?

**Comment by MrNex** [comment]
Perhaps see https://github.com/MrNex/NGen/issues/7

**Comment by ghost** [comment]
sry didnt knew with what the error has to do.
